### ISSUE TITLE
Database 

### ISSUE THREAD

**Issue by Stevenlimo** [anvil-works/anvil-runtime#15]
After logging into the postgres database, I can see the app table names listed as string values inside the ‘app_storage_access table’. But how to access the data rows from these tables such as ‘users’ using ‘psql’ command from the terminal window. Are these tables stored in the local server or remotely in the Anvil.Works server? Any ideas would be appreciated. 

----------------------------------------------
You are now connected to database "postgres" as user "postgres".
postgres=# \d
                    List of relations
 Schema |           Name            |   Type   |  Owner
--------+---------------------------+---------
 public | app_storage_access        | table    | postgres
 public | app_storage_data          | table    | postgres
 public | app_storage_data_id_seq   | sequence | postgres
 public | app_storage_media         | table    | postgres
 public | app_storage_tables        | table    | postgres
 public | app_storage_tables_id_seq | sequence | postgres
 public | background_tasks          | table    | postgres
 public | db_version                | table    | postgres
 public | scheduled_tasks           | table    | postgres
----------------------------------------------

postgres=# select * from app_storage_access;
 table_id | app_id | python_name | server | client
----------+--------+-------------+--------+--
        1 | MyApp  | table2      | full   | none
        2 | MyApp  | table1      | full   | none
        3 | MyApp  | document    | full   | none
        4 | MyApp  | users       | full   | none
        5 | MyApp  | genre       | full   | none
        6 | MyApp  | actor       | full   | none
(6 rows)
-----------------------------------------------

**Comment by meredydd** [comment]
Hi @Stevenlimo,

What you're looking at is Anvil's internal representation of the Data Tables. This isn't a bug, but I can confirm that the v1.2 release will have the same easy-to-use SQL interface that's available on our Dedicated plans, powered by Postgres views.
