### ISSUE TITLE
Users Service E-mails from_address appears to be hard coded to "accounts"

### ISSUE THREAD

**Issue by Coastline23** [anvil-works/anvil-runtime#16]
Some SMTP hosts (including mine) do not allow the email from_address to be an alias or a different to the SMTP User.

The hard coded "from_address" causes an error in this case.

An e-mail "from_address" config option would be useful here.

```
[ERROR anvil.app-server.run] Error report from client code:

  AnvilWrappedError: Invalid Addresses
  Traceback:
      <rpc>:0

  anvil-services/anvil/users.py:63

  anvil-services/anvil/users.py:469

  anvil-services/anvil/users.py:469

  app/CC_Test/Form1/__init__.py:15
```

I think this section of code shows the hard coding but it's only a guess.

From core.clj Line 232:

```
(defn send-email! [to subject text]
  (if (get-in @util/*session-state* [:users :test-email-divert])
    (swap! util/*session-state* update-in [:users :test-email-divert] concat [{:to to, :subject subject, :text text}])
    (binding [email/*use-quota* false
              email/*require-service-config* false]
      (email/send! {:from_name    (if (app-data/abuse-caution? util/*session-state* util/*app-id*)
                                    "Accounts"
                                    (str (:name util/*app*) " Accounts"))
                    :from_address "accounts"
                    :to           to
                    :subject      subject
                    :text         text}))))

```

**Comment by Coastline23** [comment]
So Meredydd, what would it actually cost to get this fixed?  

Seriously though, how much?

It appears to require changes to two sections of code, run.clj to parse a new parameter from config.yaml and core.clj to use the new parameter.  

I imagine it would take even an inexperienced clojure dev minutes not hours.

I understand that the app-server is not your focus and this is not an issue for hosted anvil hence the lack of interest.

But, aren't you just a little embarrased by the ugliness of a `"Hard Coded"` email address?  Surely not a technique taught in the Computer Lab at Cambridge!   ---- Just saying! :-)  

Come on, you know you want to!!!!!

**Comment by daviesian** [comment]
This has already been implemented, and will turn up here with our next release :)

**Comment by Coastline23** [comment]
Now, don't I feel like an A.....e! :-)

Excellent News - Thank you.
