### ISSUE TITLE
--origin works with any IP

### ISSUE THREAD

**Issue by JackN-code** [anvil-works/anvil-runtime#17]
anvil-app-server --app MyApp --origin 1.1.1.1
my ip is 48.1.1.1.1 and the above-mentioned command works without any issue. The app run perfectly well. 1.1.1.1 can be replaced by any ip

Not sure if it is a bug?

**Comment by meredydd** [comment]
It's not a bug -- it's Anvil being robust! The `--origin` you give it will be what you get from `anvil.server.get_app_origin()`.
