### ISSUE TITLE
getElement

### ISSUE THREAD

**Issue by s-cork** [anvil-works/anvil-runtime#18]
a useful javascript function would be to have 
```javascript
anvil.getElement(python_object) // must be an instance of Component (or an anvil_wrapped Component)
```
in a similar way to how 
```javascript
anvil.call
```
is used (only on the javascript side)

happy to make this PR.

**Comment by s-cork** [comment]
my question for this pr is - is it appropriate to not always return the top level component... 

e.g. a button's `._anvil.element` is probably not what the end user would expect.
Or is it better just to get to the top level element and then let the user decide where to go from there...

**Comment by meredydd** [comment]
Now implemented :)
