### ISSUE TITLE
Better error message when Custom SMTP specified in app 

### ISSUE THREAD

**Issue by mark-foerster** [anvil-works/anvil-runtime#28]
I have specified my own SMTP server in anvil online editor. Sending via the online interface works fine. When I run the app locally on the anvil runtime server, I get the following error message:

> [DEBUG anvil.dispatcher.core] Dispatch! anvil.private.email.send.v2 for feedback_form
> [ERROR anvil.dispatcher.native-rpc-handlers.util] Internal server error: 6b3710419637
> java.lang.UnsupportedOperationException
>         at anvil.app_server.secrets$get_global_app_secret_value.invokeStatic(secrets.clj:64)
>         at anvil.app_server.secrets$get_global_app_secret_value.invoke(secrets.clj:64)
>         at anvil.dispatcher.native_rpc_handlers.email$send_BANG_$fn__17149.invoke(email.clj:170)
>         at anvil.dispatcher.native_rpc_handlers.email$send_BANG_.invokeStatic(email.clj:170)
>         at anvil.dispatcher.native_rpc_handlers.email$send_BANG_.invoke(email.clj:79)
>         at anvil.dispatcher.native_rpc_handlers.email$wrapped_send$fn__17246$fn__17247.invoke(email.clj:211)
>         at anvil.core.worker_pool$with_expanding_threadpool_when_slow_STAR_.invokeStatic(worker_pool.clj:75)
>         at anvil.core.worker_pool$with_expanding_threadpool_when_slow_STAR_.invoke(worker_pool.clj:64)
>         at anvil.dispatcher.native_rpc_handlers.email$wrapped_send$fn__17246.invoke(email.clj:210)
>         at clojure.lang.AFn.applyToHelper(AFn.java:154)
>         at clojure.lang.AFn.applyTo(AFn.java:144)
>         at clojure.core$apply.invokeStatic(core.clj:659)
>         at clojure.core$apply.invoke(core.clj:652)
>         at anvil.dispatcher.native_rpc_handlers.util$wrap_native_fn$fn__12245$fn__12248$fn__12257.invoke(util.clj:82)
>         at anvil.dispatcher.native_rpc_handlers.util$wrap_native_fn$fn__12245$fn__12248.invoke(util.clj:81)
>         at clojure.lang.AFn.run(AFn.java:22)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
>         at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
>         at anvil.core.worker_pool$fn__3737$fn__3738$fn__3739$fn__3740.invoke(worker_pool.clj:28)
>         at clojure.lang.AFn.run(AFn.java:22)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> Worker terminated for IDs set() (return code -9)
> [ERROR anvil.app-server.run] Error report from client code:
> InternalError: Internal server error: 6b3710419637
> Traceback:
>   /home/ladmin/anvil/venv/lib/python3.8/site-packages/anvil_downlink_worker/anvil/_threaded_server.py:402
> 
>   /home/ladmin/anvil/venv/lib/python3.8/site-packages/anvil_downlink_worker/anvil/server.py:38
> 
>   /home/ladmin/anvil/venv/lib/python3.8/site-packages/anvil_downlink_worker/anvil/email.py:21
> 
>   /home/ladmin/anvil/feedback_form/server_code/ServerModule1.py:29
> 
>   app/feedback_form/Form1/__init__.py:26

**Comment by meredydd** [comment]
When you set up a custom SMTP server in the Anvil cloud, your credentials are kept encrypted (so your password is not in cleartext in the source code). If you want to send email from the App Server, you'll need to configure the SMTP server on the command line:

https://github.com/anvil-works/anvil-runtime#sending-email

(I'm going to keep this ticket open, as a request to make this error more helpful!)

**Comment by mark-foerster** [comment]
Thanks for your response and for clarifying how to use it.
 
I have now configured the SMTP server as follows:
`anvil-app-server --smtp-host smtp.xyz.de --smtp-port 587 --smtp-encryption starttls --smtp-username foo --smtp-password bar --app feedback_form --origin http://172.20.1.2:8080
`

Unfortunately I get the error message:

> Failed to validate "--smtp-encryption ": Expected 'ssl' or 'starttls'

Apparently `--smtp-encryption` does not accept the parameter "starttls". Neither with nor without quotation marks.

**Comment by TotalSmarticus** [comment]
Yes, I have the same  issuer as @mark-foerster. It seems "starttls" can not be passed as a parameter

**Comment by meredydd** [comment]
This should now be fixed as of 1.5.5 - please let us know/open a new issue if it recurs!
