### ISSUE TITLE
Suggestion: Use pgcli instead of psql

### ISSUE THREAD

**Issue by meatballs** [anvil-works/anvil-runtime#30]
The entry point `psql-anvil-app-server` currently uses the command line tool `psql`.

[pgcli](https://github.com/dbcli/pgcli) might be a better option because:

1. It's just better. It has several features which psql lacks,
2. It's a python library, so it can just be bundled with the app server. No need for users to install dependencies themselves, and, 
3. Windows users don't have to grapple with the pain of installing `psql`

I'm happy to put together a PR for this if there's support for the notion.

**Comment by meredydd** [comment]
Yes, we would very much be open to a PR for this!

**Comment by meatballs** [comment]
Well, I'd love to but, unfortunately, round-tuits are in somewhat shorter supply at the moment than they were when I created the issue. It may have to wait a wee while...

**Comment by meredydd** [comment]
So it goes! We'll leave the issue open with the "enhancement request" tag.
