### ISSUE TITLE
Cannot Set Single Data Table Link to NULL

### ISSUE THREAD

**Issue by yanigisawa** [anvil-works/anvil-runtime#36]
As a dedicated Anvil developer, when I use an UPDATE SQL statement to set a Link column to NULL, the value should be cleared and the link removed. 

TO REPRODUCE:

1. Clone [this App](https://anvil.works/build#clone:QO2JUOGM6ZPTNMRW=MHBY2CV2BSABMBXKUX4VM62O) to your Dedicated Anvil Account. (theoretically a local anvil-server also should reproduce the error)
2. Click the "Run Update SQL" button
3. Notice the following error is returned:

```
InternalError: Cannot update links to other rows using SQL. Please use the Python Data Tables API.
CONTEXT:  PL/pgSQL function data_tables.table_104880_update() line 13 at RAISE
```

EXPECTED BEHAVIOR

The `lookup_option` value of the `data_cache` table should be set to None.

## Relevant Code Section

In looking at the anvil-server code, it looks like this error is being generated by an automated PostgreSQL table trigger defined in `runtime/tables/util.clj` line 770. (as of git commit 44b3f5e2cf3af3412a8f5c6aa24f6ae1025cd8db)

```
... (Table trigger definition)
 (->> (for [col view-cols
      :let [COL-NAME (:VIEW-NAME col)
            ERR (get {"liveObject"      "Cannot update links to other rows using SQL. Please use the Python Data T
                      "liveObjectArray" "Cannot update links to other rows using SQL. Please use the Python Data T
                      "media"           "Cannot update Media objects in Data Tables using SQL. Please use the Python Data Tables API."}
                     (:type col))]
      :when ERR]
  (str "IF (NEW." COL-NAME " != OLD." COL-NAME ") OR (NEW." COL-NAME " IS NULL AND OLD." COL-NAME " IS NOT NULL) OR (NEW." COL-NAME " IS NOT NULL AND OLD." COL-NAME " IS NULL) THEN RAISE EXCEPTION '" ERR "'; END IF;"))
(interpose "\n")
(apply str))                                        
```

Based on my read of this code, I think the logic needs to be inverted such that if setting the value to NULL, then allow the update, otherwise RAISE an exception. 

Is this something that should be fixed, or is working as designed?

**Comment by meredydd** [comment]
Thanks for the detailed report! The next version of the App Server will support NULLing out link and Media columns.
