### ISSUE TITLE
How to serve to public when my network using a DDNS service

### ISSUE THREAD

**Issue by luxiaolei** [anvil-works/anvil-runtime#52]
Deal Anvil,

I am new to Anvil, sorry this is not an issue but more a question of how to use, hoping I am in the right place. 
I would like to serve my app to public internet (so that I can use uplink from another machine), however my host machine is under a network using DDNS service, I can't figure how should I configure. 

My host machine OS:

Ubuntu 20.04.3

I have done the followings:

1. Configure my router, that forward the host machine port 443 to outside port 443.
2. Ran the command `echo 'net.ipv4.ip_unprivileged_port_start=0' > /etc/sysctl.d/50-unprivileged-ports.conf`
3. Test it can run locally with success `anvil-app-server --app MyApp`

Then I tried the following commands to make my app accessible from outside, but all failed

    anvil-app-server --app MyApp --origin http://0.0.0.0 --port 443

    anvil-app-server --app MyApp --origin https://0.0.0.0 --port 443

    anvil-app-server --app MyApp --origin https://my-domain-name-ddns-gives --port 443

would you please teach me how should I configure/use ?  

Many thanks!

**Comment by JackN-code** [comment]
Hi luxiaolei,

You need to point my-domain-name-ddns-gives to the server ip address and run
anvil-app-server --app MyApp --origin https://my-domain-name-ddns-gives  --letsencrypt-staging

--letsencrypt-staging is for testing

letsencrypt-staging
Let's Encrypt has stringent rate limits, so if you're testing, you should use their staging service (which generates invalid certificates but has no rate limits). This option causes Anvil to use Let's Encrypt's staging service.

**Comment by luxiaolei** [comment]
Hi JackN,

Thanks for helping:) 

The domain is pointed to a ip, and I ran the command:

 anvil-app-server --app MyApp --origin https://my.server.ip.address.:443 --letsencrypt-staging

Unable to obtain ACME certificate for domains "my.server.ip.address" : unable to generate a certificate for the domains [my.server.ip.address]: acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for "my.server.ip.address": The ACME server can not issue a certificate for an IP address, url:   providerName=letsEncrypt.acme

I also created a Self-Signed SSL Certificate form [this tutorial](https://pojig.com/how-to-create-self-signed-ssl-certificate/#:~:text=To%20create%20a%20self-signed%20SSL%20certificate%2C%20type%3A%20%24,current%20directory%20unless%20another%20directory%20is%20explicitly%20specified.)

**Comment by JackN-code** [comment]
--origin https://my-domain-name-ddns-gives create a json file with certificate details in .anvil-data so you don't need to make one.

Also, make sure you can run the app with port 80 first. It is quite tricky, I need to install uncountable times before it works.

**Comment by luxiaolei** [comment]
understood, I need to try myself, thanks JackN:)

**Comment by JackN-code** [comment]
Feel free to ask any further questions. I am more than happy to help
