### ISSUE TITLE
Error on sending mails

### ISSUE THREAD

**Issue by yongalee** [anvil-works/anvil-runtime#6]
Hi,
I've moved from windows 10 to linux ubuntu and the local server is working OK until
I tried to login using email address. 

Originally, I setup my account in the app (using free acount) and then git cloned my app into local server. 

When I try to launch my app (which has email/password login option), it won't let me login using my ID and password.
First, I saw that the email server was not set correctly and I set up an SendGrid SMTP relay.
Then, if I try to login using my ID (that I've created on Anvil Server), it asks me to confirm my email inbox, and I see no email from my app. 

My local server anvil.yaml file looks correct as it shows all the values I've typed in.
![image](https://user-images.githubusercontent.com/16199520/81769316-405fdf00-9518-11ea-85c2-7476e1816c37.png)

**Comment by meredydd** [comment]
Can you supply an example application that exhibits this issue, and steps to reproduce?

Please bear in mind that the email settings for the App Server are configured on the command line or config file rather than via Custom SMTP Settings in the Anvil Editor.

**Comment by meredydd** [comment]
Hi @yongalee,

From the fact that you've reported #8, I am guessing that you now have this working.

If you have resolved an issue, please come back and either close the issue (if it was a mistake on your part) or update us with a workaround. Otherwise it's confusing for maintainers and other users.

**Comment by yongalee** [comment]
the issue was solved #7
