### ISSUE TITLE
url format for uplink to connect to runtime

### ISSUE THREAD

**Issue by j2l** [anvil-works/anvil-runtime#62]
My uplink python script registers to anvil.works/uplink and works fine.
Now, I tried to connect the uplink to my runtime and failed.
The url at https://github.com/anvil-works/anvil-runtime/blob/89b6d15bc5a1bd2bc9aee4938abd3bbf26b6e0ec/uplink/python/anvil/server.py#L345 doesn't seem to transpose as `wss://<publicip>:<port>/uplink`
Is there another url to use for runtime?

Or is it related to the missing service-core root at https://github.com/anvil-works/anvil-runtime/blob/89b6d15bc5a1bd2bc9aee4938abd3bbf26b6e0ec/server/app-server/src/anvil/app_server/run.clj#L208 and it will be fixed soon?

**Comment by meredydd** [comment]
`wss://` means an HTTPS connection; you're looking for `ws://host/uplink`!

**Comment by j2l** [comment]
Thanks @meredydd 
I use HTTPS, but I'll give ws a try.

**Comment by meredydd** [comment]
Aha - in which case I have misunderstood your question. In that case, this is the right question:

> Is there another url to use for runtime?

You want to go for `wss://my.app.server.com/_/uplink` (note `/_/`). Our next release will add an HTTPS-specific example to the docs [here](https://github.com/anvil-works/anvil-runtime#uplink-key) for extra clarity.

**Comment by j2l** [comment]
Thank you @meredydd

**Comment by j2l** [comment]
> the missing service-core root at
> 
> https://github.com/anvil-works/anvil-runtime/blob/89b6d15bc5a1bd2bc9aee4938abd3bbf26b6e0ec/server/app-server/src/anvil/app_server/run.clj#L208

Any ETA for this one?

**Comment by j2l** [comment]
After writing in your forum, mentioning in this question, asking for ETA on this one in May, writing comments on youtube, I really tried to let you know about the service -core bug. I don't get why it's not fixed.
