### ISSUE TITLE
Output of print() not visible

### ISSUE THREAD

**Issue by haimat** [anvil-works/anvil-runtime#68]
When I run our anvil app locally via the `anvil-runtime`, then I don't see the output of the `print()` statements in the server code. Is this a bug or intended behaviour? If the latter, how is one supposed to log messages with the local Anvil server?

**Comment by jpvrenen** [comment]
When I use print() in my client/server code it works.
Dec 19 08:08:41 python3[627138]: [DEBUG anvil.app-server.run] [SERVER] marker: from server code
Dec 19 08:08:37 python3[627138]: [DEBUG anvil.app-server.run] [CLIENT] marker: from client code

**Comment by haimat** [comment]
@jpvrenen Thanks, but I cannot see the server messages. Maybe I am doing something wrong.
From which function in the server code have you called `print()`?

**Comment by jpvrenen** [comment]
@haimat it doesn't really matter either callable or not callable from client functions. Perhaps some weird permission thing? Are you running from a python environment?

How I start the server:
/home/<some user>/<py environment>/bin/python3   /home/<some user>/<py environment>/bin/anvil-app-server --auto-migrate --config-file /<config file location>t/config
