### ISSUE TITLE
Environment variable DOWNLINK_WORKER_TIMEOUT is broken

### ISSUE THREAD

**Issue by chufe-dremio** [anvil-works/anvil-runtime#69]
The environment variable worked in Anvil Runtime 1.7.3, but is ignored in 1.7.6

The setting in my case was DOWNLINK_WORKER_TIMEOUT=3600. With 1.7.6 it falls back using the 30 seconds timeout.

**Comment by daviesian** [comment]
Hi @chufe-dremio

The downlink worker timeout can now be set using the `--downlink-worker-timeout` config option. This should be reflected in the documentation soon. Please let us know if the `DOWNLINK_WORKER_TIMEOUT` environment variable is still documented somewhere, so we can update those docs. Thanks!
