### ISSUE TITLE
Alert modal buttons don't display correctly

### ISSUE THREAD

**Issue by rowanvil** [anvil-works/anvil-runtime#71]
When a alert modal opens, the buttons display as blank unless they are currently being hovered over 
minimal examples app https://anvil.works/build#clone:DGV6XW35P7B6Z5GR=DZBAMMVKLU3SG7VNTNUZHBFC

**Comment by s-cork** [comment]
I imagine this is to do with prefixing modal classes in the new runtime
the theme.css has a lot of  classes like `.modal-footer` 
and we made a decision at some point to change these to `.aw-modal-footer` in the new runtime
