### ISSUE TITLE
HTTPS does not work in version 1.11.0 and 1.12.0

### ISSUE THREAD

**Issue by augustasvol** [anvil-works/anvil-runtime#88]
If I try to run it with a URL using HTTPS:

```
Traefik dashboard: http://localhost:26868/dashboard/
[ERROR anvil.app-server.run] #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [java.io.File <init> File.java 279]}]
 :trace
 [[java.io.File <init> File.java 279]
  [anvil.app_server.run$with_reverse_proxy_if_configured invokeStatic run.clj 283]
  [anvil.app_server.run$with_reverse_proxy_if_configured invoke run.clj 241]
  [anvil.app_server.run$_main invokeStatic run.clj 410]
  [anvil.app_server.run$_main doInvoke run.clj 407]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [anvil.app_server.run main nil -1]]}
```
  
  I get this error in **Ubuntu 24.04, Python 3.11, anvil-runtime versions 1.11 and 1.12**
  
  However if I try to run it in anvil-runtime version 1.10.1, it works fine without problems.

**Comment by haimat** [comment]
Same problem here.
Any updates on this issue?

**Comment by fei-yan-fentics** [comment]
I the same problem. No solution yet.

**Comment by haimat** [comment]
There is also a thread on this in the Anvil forum:
https://anvil.works/forum/t/app-server-java-lang-nullpointerexception/21041/6

No updates on this yet?

**Comment by haimat** [comment]
With latest version 1.12.2 this problem is solved.
