### ISSUE TITLE
HTTP Endpoints not working

### ISSUE THREAD

**Issue by MichalH1521** [anvil-works/anvil-runtime#92]
Hi, using the latest version of anvil app server (1.12.3 at the time of writing), I've run into a problem with api endpoints defined using the `@anvil.server.http_endpoint` decorator (`@anvil.server.route` has the exact same problem). Each time I try to access any of my http endpoints, I get a generic error in the following format:

`POST http://localhost:3030/_/api/{endpoint} 500 (Internal Server Error)`

followed by this:

`Uncaught (in promise) Error: Error: This response cannot be transmitted over HTTP. You must return either Media, a string, or a JSON-compatible object (lists/dicts/strings/numbers/None)`

Also, no matter what I try to do in the endpoint function, the code does not even seem to be running. I do not even see the output of a print that is on the first line of the endpoint function. I suppose this means, that this error is raised even before my function is called. What is more, the same error occures even when I try to access endpoints that are not even defined.

This issue is also described in [this forum post](https://anvil.works/forum/t/app-server-v1-12-error-when-serving-http-endpoints/21689/5) but there are no answers yet and the proposed fix through anvil-app-server downgrade does not work for me.

Any idea how to fix this?

**Comment by eliastor** [comment]
Hey @meredydd and @daviesian plz take a look, it's really critical for all of your clients

**Comment by eliastor** [comment]
@meredydd  @daviesian

**Comment by jpvrenen** [comment]
@MichalH1521 For reference and when testing the endpoints as mentioned on the forum only version 1.10.1 seems to work. The problem appears to be in the ‘jar’ which is downloaded when first starting the new version to accompany the relevant ‘anvil-app-server’ version.

The file is stored in ‘site-packages/anvil_app_server’, it is loaded from init in that same dir. As a test I upgraded to anvi-app-server 1.12.3 and used the old jar file from version 1.10.1. As expected the endpoint was working again but I do not reccomend this as a workaround just to pinpoint the issue.

versions
1.10.1 - anvil-app-server.20230912-112944.jar: is working
1.11.0 - anvil-app-server.20240510-143914.jar: broken
1.12.0 - anvil-app-server.20240524-175401.jar: broken
1.12.1 - anvil-app-server.20240711-134042.jar: broken
1.12.2 - anvil-app-server.20240715-162326.jar: broken
1.12.3 - anvil-app-server.20240718-132829.jar: broken

**Comment by eliastor** [comment]
@jpvrenen I've done the same exploration and received the same result.
@meredydd @daviesian plz take a look on this

**Comment by coding-with-ryan** [comment]
Hi @jpvrenen and @MichalH1521, 

Thanks for raising this.

We’ve [released v1.13](https://anvil.works/forum/t/anvil-app-server-v1-13/22395) which includes a fix for this API endpoint issue.

You can run pip install anvil-app-server --upgrade to get the latest update. Please let us know if you have any issues.

Thanks,
Ryan

**Comment by MichalH1521** [comment]
Hi,

Everything seems to be working fine again. 

Thank you very much guys, you are awesome!
